export const FISH_IMAGES = {
  'amur-bily': require('./amur-bily.png'),
  'bolen-dravy': require('./bolen-dravy.png'),
  'candat-obecny': require('./candat-obecny.png'),
  'candat-vychodni': require('./candat-vychodni.png'),
  'cejn-perletovy': require('./cejn-perletovy.png'),
  'cejn-siny': require('./cejn-siny.png'),
  'cejn-velky': require('./cejn-velky.png'),
  'cejnek-maly': require('./cejnek-maly.png'),
  'drsek-mensi': require('./drsek-mensi.png'),
  'drsek-vetsi': require('./drsek-vetsi.png'),
  'hlavacka-mramorovana': require('./hlavacka-mramorovana.png'),
  'hlavatka-podunajska': require('./hlavatka-podunajska.png'),
  'horavka-duhova': require('./horavka-duhova.png'),
  'hrouzek-beloploutvy': require('./hrouzek-beloploutvy.png'),
  'hrouzek-dlouhovousy': require('./hrouzek-dlouhovousy.png'),
  'hrouzek-kessleruv': require('./hrouzek-kessleruv.png'),
  'hrouzek-obecny': require('./hrouzek-obecny.png'),
  'jelec-jesen': require('./jelec-jesen.png'),
  'jelec-proudnik': require('./jelec-proudnik.png'),
  'jelec-tloust': require('./jelec-tloust.png'),
  'jeseter-hladky': require('./jeseter-hladky.png'),
  'jeseter-hvezdnaty': require('./jeseter-hvezdnaty.png'),
  'jeseter-maly': require('./jeseter-maly.png'),
  'jeseter-rusky': require('./jeseter-rusky.png'),
  'jeseter-sibirsky': require('./jeseter-sibirsky.png'),
  'jeseter-velky': require('./jeseter-velky.png'),
  'jezdik-obecny': require('./jezdik-obecny.png'),
  'jezdik-zluty': require('./jezdik-zluty.png'),
  'kapr-lysec': require('./kapr-lysec.png'),
  'kapr-obecny': require('./kapr-obecny.png'),
  'karas-obecny': require('./karas-obecny.png'),
  'karas-stribrity': require('./karas-stribrity.png'),
  'koljuska-triostna': require('./koljuska-triostna.png'),
  'lin-obecny': require('./lin-obecny.png'),
  'lipan-podhorni': require('./lipan-podhorni.png'),
  'losos-obecny': require('./losos-obecny.png'),
  'mnik-jednovousy': require('./mnik-jednovousy.png'),
  'mrenka-mramorovana': require('./mrenka-mramorovana.png'),
  'okoun-ricni': require('./okoun-ricni.png'),
  'okounek-pstruhovy': require('./okounek-pstruhovy.png'),
  'ostroretka-stehovava': require('./ostroretka-stehovava.png'),
  'ostrucha-krivocara': require('./ostrucha-krivocara.png'),
  'ouklej-obecna': require('./ouklej-obecna.png'),
  'ouklejka-pruhovana': require('./ouklejka-pruhovana.png'),
  'parma-obecna': require('./parma-obecna.png'),
  'perlin-ostrobrichy': require('./perlin-ostrobrichy.png'),
  'piskor-pruhovany': require('./piskor-pruhovany.png'),
  'plotice-leskla': require('./plotice-leskla.png'),
  'plotice-obecna': require('./plotice-obecna.png'),
  'podoustev-ricni': require('./podoustev-ricni.png'),
  'pstruh-duhovy': require('./pstruh-duhovy.png'),
  'pstruh-obecny': require('./pstruh-obecny.png'),
  'sekavec-horsky': require('./sekavec-horsky.png'),
  'sekavec-podunajsky': require('./sekavec-podunajsky.png'),
  'sih-marena': require('./sih-marena.png'),
  'sih-peled': require('./sih-peled.png'),
  'siven-americky': require('./siven-americky.png'),
  'slunecnice-pestra': require('./slunecnice-pestra.png'),
  'slunka-obecna': require('./slunka-obecna.png'),
  'stika-obecna': require('./stika-obecna.png'),
  'strevle-potocni': require('./strevle-potocni.png'),
  'strevlicka-vychodni': require('./strevlicka-vychodni.png'),
  'sumec-velky': require('./sumec-velky.png'),
  'sumecek-americky': require('./sumecek-americky.png'),
  'tolstolobik-bily': require('./tolstolobik-bily.png'),
  'tolstolobik-pestry': require('./tolstolobik-pestry.png'),
  'uhor-ricni': require('./uhor-ricni.png'),
  'vranka-obecna': require('./vranka-obecna.png'),
  'vranka-pruhoploutva': require('./vranka-pruhoploutva.png'),
  'vyza-velka': require('./vyza-velka.png'),
  
  'default': require('./kapr-obecny.png'), 
};

export const getFishImageKey = (speciesName) => {
  if (!speciesName) return 'default';
  
  return speciesName
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // Odstraní diakritiku
    .replace(/\s+/g, '-')             // Nahradí mezery pomlčkami
    .trim();
};